### ISSUE TITLE
Current implementation of PIE incorrect in boxplot

### ISSUE THREAD

**Issue by rueuntal** [MoBiodiv/mobr#135]
It's currently being calculated as the Simpson's index, 1 - pi^2, while it's actually rescaled Simpson's as (1 - pi^2) * N / (N - 1) (see Hurlbert paper). Not sure if the issue also applies to ENV_PIE?

**Comment by dmcglinn** [comment]
Thanks for catching this @rueuntal I'll get this fixed after getting #140 merged. Can you remind me again what ENV_PIE is or did you mean beta_PIE?

**Comment by rueuntal** [comment]
Sorry my bad. I meant ENS_PIE.

**Comment by dmcglinn** [comment]
Ok I'll take a look in the Jost 2004 paper to see how he lays that out.

**Comment by rueuntal** [comment]
Thanks!

**Comment by FelixMay** [comment]
Hi Dan, hi Xiao,
ENS_PIE is the effectve number of species based on PIE (Simpson index) so if p_i is relative abundance PIE = 1- sum(p_i^2) and ENS_PIE = 1/sum(p_i^2)

See Jost 2006 Entropy and diversity, Table 1. 

Well, maybe ENS_PIE is not a good word, Jost calls it D2 I think. ENS_PIE is Jon Chase terminology ;o)

The corresponding (multiplicative) beta diversity is then D2 (gamma)/D2 (alpha). (Jost 2007: Partitioning Diversity into Independent Alpha and Beta Components)
For the implementation in `mobr` I used the function `vegan::diversity(x, index = invsimpson)`, which should be alright.

**Comment by dmcglinn** [comment]
Hey @FelixMay the problem is that PIE != 1 - sum(p_i^2) according to Hurlbert. Instead as @rueuntal points out PIE = (1 - pi^2) * N / (N - 1) when one is sampling without replacement (i.e., finite sampling domain). The rest of our rarefaction work always assumes finite sampling domain so I agree with @rueuntal we should go with the rescaled version of this metric. The `vegan` implementation and my own implementation in the function `calc_PIE` are not quite correct for our purposes here. I suppose that ENS_PIE also suffers from this difference in assumptions.

**Comment by FelixMay** [comment]
Hey @dmcglinn, alright that makes sense, but it seems that can be easily fixed. Should I put this task on my list or do you plan to adapt the calculation of PIE?

**Comment by dmcglinn** [comment]
Go ahead and modify `calc_PIE` with a note that our implementation is based on Hurlbert 1971 equ 3 which assumes sampling without replacement or if you would rather I can do it after you have finished implementing the group level tests so as to not introduce conflicted merges.

**Comment by dmcglinn** [comment]
@FelixMay introduced the changes I suggested in #140 but now I see that when there is a singleton that Hurlbert's 1971 formulation results in an undefined value because N  / (N - 1) is undefined when N = 1. Looking back to Hurlbert 1971 I also see that he noted the estimator only worked with N >= 2. @rueuntal do you have a recommendation for how to treat these undefined samples. I would be temped to set PIE equal to zero because clearly if there is one individual the probability of encountering another individual is zero.

**Comment by FelixMay** [comment]
Hi @dmcglinn, I already worked on that yesterday (but do not push the changes yet) and so far I set PIE to NA when N = 1. Essentially because drawing WITH REPLACEMENT is impossible. But PIE = 0 is another option. Let me know what you prefer. This will of course have consequences for averaging the sample data later on.

**Comment by rueuntal** [comment]
Looks like issues in this thread have all been addressed.
