### ISSUE TITLE
inconsistency between concept paper and method paper

### ISSUE THREAD

**Issue by rueuntal** [MoBiodiv/mobr#155]
@dmcglinn @FelixMay - I'm going over Jon's concept paper, and there's an inconsistency in the description of the methodology of the alpha-gamma scale analysis, so I want to double-check that the three of us are on the same page before bringing it up to Jon and making edits. (I'm using GitHub instead of email in the hope of making our discussion easier and more tractable; this issue doesn't have much to do with the code.)

If you read the last paragraph on page 20 to the end of page 21, and look at figure 4 on page 22, it is described that a number of metrics on the alpha and the gamma scales (e.g. rarefied S, asymptotic S, PIE) are computed based on the spatially-constrained rarefaction curve, which I don't think is being used. My understanding is that these calculations are all done using the individual rarefaction curves. Is that right?

**Comment by dmcglinn** [comment]
Hey @rueuntal thanks for pointing this out. The paragraph does make it seem like those metrics are computed from the spatially constrained rarefaction curve but you are correct they are not. All of them are calculated from the individual based rarefaction curve. It also appears the description of the spatially constrained rarefaction curve is incorrect (start of last paragraph pg 20). 

> the spatially-constrained rarefaction curve ... keeps the spatial information intact, but controls for differences in N while retaining differences in both the SAD and aggregation.

This would only be strictly true if we were referring to a curve constructed from a stem map were spatially sampling individuals rather than plots but we've always referred to a curve that controls for number of plots sampled but not for number of individuals (N). We can convert from one to the other but then why is the individual rarefaction curve longer than the spatial rarefaction curve in Fig 4b? I find this figure pretty confusing overall. I also have trouble with Box 2 in which the species accumulation curve (SAC) is described as being similar but distinct from rarefaction curves. This ties in I think to my confusion over figure 4.

**Comment by rueuntal** [comment]
@dmcglinn thanks for the prompt reply. My reading of 4b is that those two curves are both spatially-constrained rarefaction curves, at alpha and gamma scales. If they are individual-based rarefaction curves instead would it make sense to you?

**Comment by dmcglinn** [comment]
Yea I think that is what the figure is attempting to illustrate but it really only makes sense in our framework for the individual based rarefaction curve because we've setup our sampling domain to have individuals in plots and not individuals with x-y coordinates. So I think figure 4 would be fine if it was just on the individual based rarefaction curve instead of the spatial species accumulation curve.

**Comment by dmcglinn** [comment]
I think before we bring this up to Jon and the rest of the group it would be great to come to a consensus on the curve names. Here is my personal vote of a naming hierarchy system to adopt. So all curves we discuss are all different flavors of species accumulation curves

* Species-accumulation curves 
    * species area relationship
         * nested
              * continuous
              * non-continuous  
         * island
    * spatial 
        * nearest neighbor plot
        * nearest neighbor individual
    * rarefaction curves
        * individual 
        * plot (aka non-spatial species accumulation curve)

**Comment by rueuntal** [comment]
I agree, having a consensus on names is important so that we don't keep talking past each other. Just to double check - the spatial curves that we have are spatial - nearest neighbor plot, correct? And the only difference between that versus a nested continuous/noncontinuous SAR is the latter uses a sliding window to construct (which wouldn't work in irregular designs)? 

I'm also tempted to not call the last curve plot-level rarefaction, to avoid the confusion with sample-based rarefaction.

**Comment by dmcglinn** [comment]
Yes we are using spatial nearest neighbor plot species accumulation curves which we refer to as spatial accumulation or spatial rarefaction curves in our paper. You have noted that because there is no rarefaction going on with this curve you would prefer we didn't call it a rarefaction curve and I'm good with that. The only argument for sticking with spatial rarefaction is that was the first name applied to it by Chirarucci et al. So if you define rarefaction at bit more broadly as any expression of diversity that controls for sampling effort then our curve could be considered a "rarefaction curve".  

I agree that the spatial accumulation curve and the SAR are identical with the exception of the moving window and the flexibility our curve provides for irregular designs

**Comment by dmcglinn** [comment]
Oh and I'm fine going with sample-based rarefaction rather than plot-based

**Comment by FelixMay** [comment]
Hi @dmcglinn and @Xiao,
Thanks for your thoughts! I fully agree that consistency and clear terminology is important. I think what is confusing in Fig. 4B is that two concepts are mixed up: 

1. Individual based rarefaction vs. spatial (nearest neighbor) accumulation (at the gamma-scale
2. Individual based rarefaction at the gamma-scale vs. individual based rarefaction at the alpha scale

In the text these two things are equated, but this is easy to overlook. See page 20 at the bottom:

From this curve, **or simply from the rarefaction curve collected from a smaller (local) scale (dashed line in Figure 4B),** we can calculate several parameters that help in our disentanglement of the components underlying the SAC.

However, I think while this link between the two concepts is clear to Jon it does not become clear enough for readers. I think it needs more explanation why individual-based rarefaction curves at the sample scale are similar to the lower part of spatial nearest neighbour accumulation curves at the gamma-scale. And of course there should be consistent terminology between text and figures.

**Comment by rueuntal** [comment]
@dmcglinn @FelixMay thanks for the feedback! Looks like we are all on the same page for the most part. Just a few more minor clarifications:
@dmcglinn - I'm OK with calling the spatial curve "spatial rarefaction" if that's already established by  Chirarucci et al. But along the same vein I'd be inclined not to use plot-based rarefaction, or sample-based rarefaction, for the nonspatial curve, as that's also an established & different concept. What do you think?

@FelixMay - what confuses me is that Jon brought up three curves - SAC (which seems to be equivalent to our spatial curve), spatially-constrained rarefaction (which I don't think we used?), and individual-based rarefaction. In fact we only need the individual-based rarefaction at the alpha and the gamma scales to calculate all metrics for this  part, right?

**Comment by FelixMay** [comment]
@rueuntal Yes, in the `get_mob_stats` function we just use individual-based rarefaction at the sample (=alpha) and treatment group (=gamma) scale. I think in the Figure Jon wants to show these two curves. But I suggest to contact Jon soon and discuss this terminology with him directly.

**Comment by dmcglinn** [comment]
Sorry @rueuntal can you clarify what name you prefer for the plot / sample based rarefaction (i.e., the non-spatial species accumulation)?

**Comment by dmcglinn** [comment]
I guess technically we don't use plot / sample based rarefaction in our framework so we should stick with a new term like "non-spatial species accumulation" to emphasize that this should not be confused with those methods. Is that what you were trying to point out?

**Comment by rueuntal** [comment]
Yeah exactly. When people hear sample-based rarefaction or a similar term they may think it's the same as the one in Colwell et al. I believe we made that clear in writing in our ms but it might still be good to prevent the readers from making that connection subconsciously.

**Comment by dmcglinn** [comment]
Ok so I think we've formed a consensus amongst ourselves on terminology. I'm still not super sure where to place the non-spatial rarefaction curve I placed it as a special kind of individual based curve because we randomize the location of all the individuals as well as plots. 

* Species-accumulation curves 
    * species area relationship
         * nested
              * continuous
              * non-continuous  
         * island
    * rarefaction curves
        * individual-based
            * random 
            * spatial nearest neighbor
            * non-spatial - a new kind of curve we have created which is a rescaled individual based curve based on the average density of individuals between two treatments
        * sample-based 
            * random - captures only within plot spatial autocorrelation
            * spatial nearest neighbor - captures both within and between plot spatial autocorrelation

**Comment by rueuntal** [comment]
Very cool @dmcglinn ! I'd agree that the nonspatial curve should be categorized under individual-based rarefaction, since that's exactly what it is, only with rescaling. 

So the spatially-constrained rarefaction in Chiarucci et al is identical to our spatial curve, correct? Shall we use spatially-constrained rarefaction, or SAC?

**Comment by dmcglinn** [comment]
Our spatially-constrained rarefaction is identical to Chiarucci with the exception to how the identified the next nearest neighbor in which case they used a k-nearest neighbor algo and we just used the minimum distance. I would prefer to use spatial rarefaction curve in our paper to follow their present and because I see all of these curves as SACs. So I don't think that SAC is a good term for any single curve in our context when all the differences between the curves matter.

**Comment by dmcglinn** [comment]
If you're ok with this last bit then I'll send this hierarchy out to the broader group and if everyone is ok with it then I'll make changes to our methods paper which I think we be minimal.

**Comment by rueuntal** [comment]
Not that this is super important, but I think their KNN approach is very similar if not the same to ours, the only difference being that we requires the starting points to be within a plot, then it's still the nearest neighbors (for each plot in our case), right? 

I can see your reasoning against SAC, spatial rarefaction curve it is then! And sending out to the broader group sounds great (was gonna offer to do that before seeing your update :) )

**Comment by dmcglinn** [comment]
KNN approach?

**Comment by dmcglinn** [comment]
Oh k-nearest neighbor (sorry your stat speak baffles the silly ecologist ;)) Yea I think the approaches will be very closely related the k-nearest neighbor somehow deals with ties in a maybe a more elegant way then our approach.

**Comment by dmcglinn** [comment]
After speaking with Nick and Jon and ESA we realized that the concept only needs to mention the individual-based rarefaction curve that it does not derive any statistics from any of the other curves so there may not be much use in describing them and introducing additional jargon that is inconsistent with the methods paper. I'm going to re-read the concepts paper with this in mind and see if we can weed out all mentions of the other curves without losing important content
