### ISSUE TITLE
install cumbersome because of dplyr

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#162]
we need to look close at the boxplot code to see if dplyr is really needed. This package is a real pain in the butt due to all its dependencies that do not install themselves.

**Comment by rueuntal** [comment]
Ref #149 . We'd probably want to discuss it with Shane.

**Comment by FelixMay** [comment]
Hi @dmcglinn ,
I think the problem is not `dplyr`, but `devtools`. It seems it does not properly dependencies of dependencies, e.g. [devtools problem](https://stackoverflow.com/questions/38425529/does-install-github-recursively-install-dependencies/38439733#38439733).

My suggestion is to keep `dplyr`, but update the readme file in our repo with explicit installation of second order dependencies and/or hints how to update `devtools` properly.
And in the midterm put `mobr` on CRAN and then we do not rely on `devtools` anymore. Just before the birth of our baby I started preparing `mobsim` for CRAN, but of course this is still work in progress

**Comment by dmcglinn** [comment]
Hey @FelixMay I agree with this approach and I added additional install instructions to the README.md in ab894f2c6000193e266a71605df8dcaf7efa9773 and the vignette in /870013e6240333e797a4cf8f2151b94ad68c147a
