### ISSUE TITLE
user requests for graphics improvements

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#176]
@nathanbaker04 has provided the following feedback and comments on the package.

>Before I forget (because I probably will), I want to run some ideas past you for the mobr package in terms of visuals and also for the help package. So I'm noticing that the help file for the "get_mob_stats" in R is often having an error in the link, and requires an R session restart. That's the only one I ever have issues with, and I'm almost positive it's triggered by an update from github when I re-download mobr, so that's probably normal and not an issue. But for visuals (I'll have to show you this tomorrow), I notice that the y-axis label for abundance boxplot is squished into the axis numbers, and the x-axis labels are always so small. I know that can be changed by the individual user, but figured it may be worth consideration to increase the size. Not sure. Just figured you'd like to know.

**Comment by FelixMay** [comment]
Hi @dmcglinn, the first problem sounds like a tricky and potentially hard to reproduce error. Similar with the figure, because this will depend on the specific monitor and RGui Software. Should I have a look at these things on my machine? If yes, I would be grateful for a screenshot from nathan. Or will you take are of this.
