### ISSUE TITLE
get_mob_stats: several f_0 results as zero and beta_f_0 as NA?

### ISSUE THREAD

**Issue by elslabbert** [MoBiodiv/mobr#218]
Hi there,
I have been working with the output form the get_mob_stats function to do further analyses and have noticed that so of the results for the f_0 come out as zero and beta_f_0 are NA. Is that ok in light of how the function works and a "real" result based om my data, or has something going wrong? I am not getting any warning messages, so not sure where to start checking if something is wrong.

Here is my code (data attached):

[testdat&coords.zip](https://github.com/MoBiodiv/mobr/files/2273653/testdat.coords.zip) 
```r
# # === Run mob code SUBPLOT level comparing land use =============
test_mob_in = make_mob_in(testdat, testcoords, coord_names = c('lon', 'lat'), latlong = T)
print(test_mob_in)

test_stats = get_mob_stats(test_mob_in, group_var = "group", index = c("N", "S", "S_n", "f_0", "S_PIE"), n_perm=199)

# extract results from mob_stats for further analyses steps
testdat.result <- as.data.frame(test_stats$samples_stats)
```
In this data frame there are many 0's for f_0 and NA results for beta_f_0. Is this ok? oR is there something incorrect in my script/data input?

Thanks for your inputs!

Best,
elslabbert

**Comment by dmcglinn** [comment]
Hey @elslabbert thanks for your question. This is not a bug. Although we originally did promote the `f0` metric as a way to quantify the patterns of the rare species we are less enthusiastic about its use at the current time. This is reflected in the fact that we dropped `f0` as a default metric from `get_mob_stats` and we have dropped it from our [preprint]([https://www.biorxiv.org/content/early/2018/01/07/244103). One of the primary reasons we decided to drop f0 is what you are currently experiencing. This metric uses the Chao1 estimator of `S_asymp` to estimate how many missing species their are. This particular estimator only examines patterns in the singletons (f1) and doubletons (f2) species. If you do not have any singletons or doubletons then your observed S will equal the estimated S_asymp and f0 will be zero. In these scenarios `beta_f_0` will be `Inf` because of a division by zero which our code converts to an `NA` value. So in other words `f0` and `beta_f_0` are less stable than we would like out of our estimators. There is also the problem that `S_asymp` doesn't really exist unless you are thinking about it at the global level - this concept seems particularly problematic for bacteria species with their rapid rates of speciation. Rather than using `f0` as an indicator of patterns of diversity dominated by rare species we suggest that user's follow Jost's advice and consider that `S` is quite sensitive to rarespecies as it simply reflects presence or absence and `S_PIE` is more sensitive to common species. Also its worth noting that McGill's 2011 book chapter found that S was highly correlated with many other metrics of the degree of rarity in a community.

**Comment by dmcglinn** [comment]
One other quick note about using github's issue system. Your issues are rendered in markdown here's a little link about how to format them better: https://guides.github.com/features/mastering-markdown/

With respect to code chunks you should wrap them in back ticks ` take a look at how I edited your comment above to see an example. Thanks again for posting!

**Comment by dmcglinn** [comment]
@elslabbert can I mark this as resolved? Thanks!
