### ISSUE TITLE
Rethink the sample-based rarefaction (sSBR) curve

### ISSUE THREAD

**Issue by T-Engel** [MoBiodiv/mobr#225]
Hi all,

I would like to challenge the way we draw the spatially constrained, sample-based rarefaction (sSBR) curve. Here a quick reminder of how it's implemented currently: 
> "The first curve is the spatial, sample-based rarefaction (sSBR) (spatially-constrained
rarefaction Chiarucci et al. 2009). It is constructed by accumulating plots sampled within a treatment based on their spatial position such that the most proximate plots are collected first. One can think of this as starting with a target plot and then expanding a circle centered on the target plot until one additional plot is added, then expanding the circle until another plot is added, etc. In practice, every plot is used as the starting target plot and the resulting curves are averaged to give a smoother curve. If two or more plots are of equal distance to the target plot, they are accumulated in random order."

I think that the way we handle plots of equal distances (i.e. choosing at random) becomes problematic when the plot design is very regular which results in many of such ties in the distance matrix. This is the case in the ant data set that we are exploring at the moment. Let me show you what I mean. Below you have the plot design. You can easily see that there are many samples of equal distances which means that we use a lot of coin flipping for the construction of the sSBR curve.

![image](https://user-images.githubusercontent.com/37897372/46656529-90ddc080-cbae-11e8-9a4b-1c9b5e969f39.png)

Let's do one example starting with a focal sample A4. The next sample to include would be either A2 or A3. We flip a coin to decide the order in which we are including them (e.g. first A2, then A3). The fourth sample is easy again; it has to be A1 because it is the 3rd closest neighbor of A4. Now, we move on to the 5th sample and it is taking us either to subplot B (i.e. sample B3) or to subplot C (i.e. sample C2). The coin decides it'll be sample B3. According to our algorithm, the 6th sample to include is automatically C2 because it had a tie with B3.
I think this is problematic. Why would we move all the way from subplot B to C without finishing all the plots in B? Wouldn't it be a much better representation of the spatial structure if we instead add sample B1 first? It seems much more intuitive to me to finish off the neighborhood of all the samples that have already been included rather than just focussing on the distance to our starting point A4. Do you share this feeling?

I went back to the original paper Chiarucci et al. (2009) that introduces the sSBR to see how they deal with this problem. They are very aware of this but don't investigate it any further:

> "In creating a spatially-constrained curve, we combine adjacent sampling units. To do that, we must first decide what constitutes “adjacent.” Various definitions can be applied (Dale 1998), among these are: k-Nearest Neighbor (k-NN, see e.g., Hastie et al. 2001 and references therein), k-Nearest Centroid Neighbor (k-NCN, e.g., Rutkowski et al. 2004), natural neighbors (Voronoi 1907), and γ-neighbors (Veltkamp 1992). k-NN consists of choosing the n neighbors closest to the original sampling point. k-NCN consists of choosing the next sampling unit that is closest to the centroid of the already selected units. Natural neighbors are defined through a Dirichlet tessellation (also referred to as a Voronoi tessellation, see Dugan 2005). With γ-neighbors an asymmetric notion of closeness is applied. In this paper, we use a method based on the k-Nearest Neighbor (k-NN). A discussion of the effects of different neighborhood rules is beyond the scope of this paper."

Further down in the conclusions they add:

> "Our exploration of these questions leaves several issues unaddressed. As mentioned previously, the effects of different neighborhood rules used to construct the curves need to be investigated. In this paper the areas all had the same density and spacing of the sampling units. Additional work is needed to look at the effects of both the mean and variance in spatial lag. Often, the spatial density of sampling units is lower for larger areas and therefore different methods are needed than those adopted here. Future refinements of the proposed approach might include constraining the samples based on the extent of the n sampling units, rather than on whether the units are adjacent."

To sum up, there are alternatives to the approach that we are using and some of them might be better suited for our application. As I am writing this, I am realizing that it's not necessary the coin flipping that I find problematic but rather the way we define the neighborhood rules in general. So, can we think about how we could refine them? 

Coming back to my example above, I think it would be useful to think of "neighborhood" as the neighborhood of all the plots already accumulated rather than proximity to the starting point. One way to implement this would be to consider the previously accumulated samples as a new single sample that is located at the centroid. So, we would include the sample that is closest to the centroid of all the previously accumulated samples. Thus, in the figure above we wouldn't after only 6 samples already cover a large portion of the spatial extent (i.e. subplots A, B, C). This approach sounds similar to the k-Nearest Centroid Neighbor method that Chiarucci et al. mention. I had a brief look at the reference they cite and it seems to describe the same thing with more maths but I'm not entirely sure...

As I only joined the mob recently, I am not sure if you have already discussed this issue. So, I apologize for possibly reopening old wounds. I guess my questions to all of you are the following:

- Did you discuss the neighborhood rules and explore different options?
- Why did you decide to use the the k-Nearest Neighbor approach adopted by Chiarucci et al?
- Are you aware of any literature that picks up the issues raised by Chiarucci et al?
- Do you think the results will change qualitatively if different approaches are used?
- Do you think we should explore this further for mobr?

**Comment by dmcglinn** [comment]
Hey Thore and Nick, 

Thanks for these great ideas. Thore in response to your questions I agree with everything Nick said and I'll just add that I was aware that Chirarucci used the k-means spatial clustering method but that I didn't look into it closely. I'm fairly confident there isn't much of a literature on this regarding spatial rarefaction methods because I tried to search extensively for papers on the topic (although I wasn't aware of the Japanese work so maybe take that into consideration).  I agree with you that the ties are not really satisfactorily handled and confound the conversion of # of samples into spatial distance apart. Our method is built in part on the assumption that as # of samples increases the geographic distance between the focal sample and the next added sample increases, but with regular transects or grids this is not always the case as you pointed out. You can have sampled 3 sites but your maximum lag may only be 1 unit of distance (e.g., plots A1, A2, and A3 in your diagram). 

I'm not too concerned with the tied cluster jumping phenomena you described for the reasons Nick suggested. I agree with him that a species or focal quadrat perspective is likely more useful than a moving centroid approach. However, I may be wrong. I could certainly see how we could easily change out algo so it minimizes two distance functions: the original plot distances and the moving centroid distances. This would ensure that groups of plots are sampled together as the algo increases spatial extent. 

An additional issue with our approach that I think is even more important is that if we have different sampling designs in our treatments then we introduce a scale mismatch by using # of samples as a measure of spatial scale. In our methods paper, we urge a restricted usage of the method to similar sampling designs but I don't think this is realistic when folks are considering many observational datasets. We did discuss this and we decided ultimately if we want to tackle this well then we may have to move away from thinking about # of samples accumulated and move to spatial distance apart between quadrats. This is why I created the function `avg_nn_dist` which computes the average distance lag of the nth nearest neighbor. This has an effect on ties in that it compresses the x-axis of the curves and it provides a clearer glimpse of scale specific comparisons between treatments. I'm not sure if this function is really the best approach as it takes the existing sSBR and then tries to back calculate what distances those averages apply to. It is possible that mathematically this is not the "correct" way to accomplish what we are interested in but it is quick and dirty. I suggest we take a look at the GSMNP ants using avg_nn_dist to see if this helps us to gain any additional clarity on the aggregation effect. We will have to go in an add a step where # of samples is converted to distances prior to the slopes being estimated.

**Comment by ngotelli** [comment]
Hi Dan and Thore:


Those Japanese papers are actually from the early 1980s:


Kobayashi, S.  1982.  The rarefaction diversity measurement and the spatial distribution of individuals. Japanese Joumal of Ecology 32:255-258.

Kobayashi, S.  1983.  Another calculation  for the rarefaction diversity measurement for different spatial distributions. Japanese Joumal of Ecology 33: 101-102.

Smith, E.P., P.M. Stewart, and J. Cairns, Jr.  1985. Similarities between rarefaction methods. Hydrobiologia  120: 167-169.

As far as I am aware, these are the earliest references to spatial effects on rarefaction. I haven't read these in a  long time, but I doubt they will have anything new for us.

Dan's point about problems with spatial scale and sample accumulation in observational studies is a good one. I would be happy to see the mobr framework expanded to provide additional tools for dealing with spatial scaling.

Also, the mobr framework still relies mostly on a  dichotomous yes/no decision about the effects of N, SAD, and spatial structure. I would love to figure out some kind of variance partitioning method (x% of the differences in diversity between treatments attributed to N, but only y% to SAD and z% to spatial structure), but I have not been able to figure out how to do this.

Best,

Nick

________________________________

**Comment by T-Engel** [comment]
Hi Nick and Dan,

thank you for your responses.
I think you are right that the sSBR (regardless of the neighborhood rules) will always be relatively close to the random sample based accumulation (due to constraints imposed by S, N, and SAD). And the magnitude of the deviations from this random curve is probably not strongly affected by the clustering algorithm, either. However, I think that the position of the deviations along the x-axis will be influenced by the order in which the samples are accumulated (i.e the clustering algorithm).
Therefore, I think the scale at which we find the aggregation effects might differ between algorithms. As long as our x-axis in the multiscale analysis remains "Number of samples", I think this might be a problem.

I agree that moving towards a "Distance" x-axis is what we should do in general.  Not only would that allow more meaningful comparisons among sites with different extents but also the biological interpretation of the results would be more straightforward. Maybe we can open another issue dedicated to this important question. Thanks for moving forward with `avg_nn_dist`, Dan!

Coming back to the k nearest centroid neighbor method, I created a function to do that [in my fork](https://github.com/T-Engel/mobr/blob/master/R/k-NCN_curve_functions.R). It can probably be made more efficient but it should do the job for now. I attached a PDF comparing the different types of sample-based curves in all the plots of Nate's ant data (i.e. rarefaction(method="samp"), rarefaction(method="spat") and my kNCN_average()). You can see that at most sites the spatially constrained curves are only marginally different from the random one which suggest that the aggregation effects are not very strong in general. Yet, for the sites that show aggregation, the k-NN and k-NCN show different trajectories (identifying the effects at different scales). I guess the differences between the algorithms are the bigger the more clustered the sample layout. 

[sample_based_curves.pdf](https://github.com/MoBiodiv/mobr/files/2473194/sample_based_curves.pdf)

At this point I am not convinced if one method is better than the other but i think its worth noting that they can be qualitatively different at the the site level. I haven't yet explored how robust the results of the multiscale analysis across sites are to this. I might try to do that next. 

I agree that the fixed focal sample is a good approach if we are aiming for a "Distance" x-axis. However, in that case I am not sure anymore if we want to accumulate species or if we should rather look at distance decay (Dan, you suggested distance decay as an alternative when I showed you my DBH based accumulation curves in trees). 
If we have a "number of samples" x-axis I believe that the centroid approach might be suitable because it follows the accumulation process through space: As we accumulate samples (regardless of space), we never keep the focus on the initial sample but instead add our subsequent samples to the pool of all previously accumulated samples. In a spatially constrained accumulation, I think this constantly evolving pool should also have evolving coordinates that start off at the focal sample but diverge from it as we include more samples. This would be the centroid.
Yes, Nick, the cetroid would move towards the centre of the site but I think that doesn't make it similar to the random accumulation. Close by plots will still be included first, won't they?

Best,
Thore
