### ISSUE TITLE
Continuous multi-scale needs separate grouping and enviornmental variables 

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#226]
Currently the function `get_delta_stats` on the `dev` branch only takes `group_var` as an input which is the grouping variable. If the analysis is continuous (i.e., `type = continuous`) then it is possible that two groups will have the same enviornmental value along a gradient (e.g., same elevation) but we wish to keep them in separate groups because for example they are members of different surveys. To accomplish this the `env_var` argument needs to be added to the function.

**Comment by T-Engel** [comment]
Oh good, you had already considered this! I noticed this problem, too. Sorry, I didn't see this Issue earlier. I think it's important that we fix this. Otherwise, samples that happen to have the same value along the gradient but belong to different groups will be lumped together. 
Have you made any progress on this? I think it won't be difficult. We just need to make sure to aggregate samples by `group var` and calculate the stats (e.g. beta coefficients) along `env_var`. One question that might come up in the future is, whether the `env_var` has to be homogeneous within groups or whether it can vary. I think it is possible for alpha samples within a group to have slightly different values along the gradient of interest (e.g. slightly different altitudes). Can we accommodate this?
