### ISSUE TITLE
calculation of betaC fails when there are at least 1 doubleton but no singletons

### ISSUE THREAD

**Issue by dmcglinn** [MoBiodiv/mobr#266]
On the following lines: 
https://github.com/MoBiodiv/mobr/blob/dev/R/beta_C.R#L86-L97

It can be seen that the variable `A` is not defined when `f1` equals 0 (i.e., no singleton species) but `f2` is a positive value (i.e., there are some doubletons). 

@T-Engel any advice for how to proceed here? Thanks!

**Comment by T-Engel** [comment]
Hey Dan,
Thanks for catching this! Did you actually run into problems with this or is this just a hypothetical question based on your reading of the code? I’m asking because I haven’t been able to produce an example community where this becomes relevant in practice.

I suspect this case is not defined in the code because it probably cannot happen in practice. Remember this section of the code deals with extrapolation, so that is situations where the reference coverage is larger than the observed coverage. For the case you describe (f1=0, f2>0) the estimated coverage is always already 1, following Chao’s  and Shen’s coverage estimator (i.e. Eqn 4a, https://esajournals.onlinelibrary.wiley.com/doi/10.1890/11-1952.1). Therefore, extrapolation is not applicable and this section of the code will never become relevant for the given scenario. Does that make sense?

I copied this code from INEXT and they don’t seem to define the case either.

So, I would tend to say we can leave it as is. Unless of course, you’re getting weird results for something. Let me know your thoughts!

Von: Dan McGlinn ***@***.***>
Gesendet: Freitag, 6. Mai 2022 21:36
An: MoBiodiv/mobr ***@***.***>
Cc: Engel, Thore ***@***.***>; Assign ***@***.***>
Betreff: [Extern] [MoBiodiv/mobr] calculation of betaC fails when there are at least 1 doubleton but no singletons (Issue #266)


On the following lines:
https://github.com/MoBiodiv/mobr/blob/dev/R/beta_C.R#L86-L97

It can be seen that the variable A is not defined when f1 equals 0 (i.e., no singleton species) but f2 is a positive value (i.e., there are some doubletons).

@T-Engel<https://github.com/T-Engel> any advice for how to proceed here? Thanks!

**Comment by dmcglinn** [comment]
Thanks for the quick reply! This was triggered by an empirical case that had no singletons and one doubleton. This function was breaking and saying A was not defined.

Thanks!

Dan

**Comment by dmcglinn** [comment]
Reminding myself I need to follow up on this. Not sure if this was ever resolved.

**Comment by dmcglinn** [comment]
this appears to be resolved. Chat now returns reasonable values when there are zero f1 but some f2 in the sad.
